Basic backend dev branch
ZuydUniversity/B2C6_B2C_Backend pull request #34
Opened 2024-05-24 08:55 UTC by Agressie

Created the basic backend with templates to work with, also added an test folder.

2024-05-24 10:36 UTC, Toffeegaming requested changes
sommige filenames zijn met hoofdletter en andere zonder, kijk hier ff naar

2024-05-24 10:36 UTC, Toffeegaming commented on Backend/UnitTest/Helloworldtest.py
FastAPI heeft [ingebouwde testing](https://fastapi.tiangolo.com/tutorial/testing/), is er een reden dat deze niet gebruikt wordt?

2024-05-24 10:36 UTC, Toffeegaming commented on Backend/UnitTest/starttests.py
zelfde opmerking als op Backend/UnitTest/Helloworldtest.py

2024-05-24 10:36 UTC, Toffeegaming commented on Backend/main.py
is app.debug = True hier nodig?

2024-05-24 10:36 UTC, Toffeegaming commented on Backend/routers/HomeRouter.py
toutch ipv touch, en willen we alle comments in het Engels?

2024-05-24 11:57 UTC, Agressie commented on Backend/UnitTest/Helloworldtest.py
Ja, ik kreeg deze niet fatsoendelijk werkend vandaar dat ik de omweg van pytest gebruikt heb.

2024-05-24 11:57 UTC, Agressie commented on Backend/main.py
Ja, zolang we bezig zijn met ontwikkeling wil je die op True hebben, je krijgt namenlijk op dat moment goed in de browser te zien wanneer iets misgaat.

2024-05-24 11:58 UTC, Agressie commented on Backend/routers/HomeRouter.py
Lijkt mij wel het meest makkelijke om 1 taal aan te houden. We moeten ook in engels coderen dan ga ik er vanuit dat engels ook de comment taal is.

2024-05-24 12:02 UTC, Toffeegaming commented on Backend/UnitTest/Helloworldtest.py
Die ingebouwde werkt ook namelijk via pytest, wil je anders dat ik er ff snel naar kijk?

2024-05-24 12:03 UTC, Toffeegaming commented on Backend/main.py
Ait, dan moeten we die wel ff in de gaten houden en zorgen dat we die niet vergeten te veranderen/ daar zsm een environment variabele van maken.

2024-05-24 12:05 UTC, Toffeegaming commented on Backend/routers/HomeRouter.py
Ik weet namelijk dat veel mensen hun Engels wat werk kan gebruiken en dat, voor de mensen die minder sterk zijn in programmeren, ze al uit zichzelf Nederlandse comments schrijven en daarom daardoor ook sneller code kunnen begrijpen als ze niet die extra vertaalstap hoeven te maken.

Denk dat dit voor nu prima is, maar dat we hier een consensus in de groep over moeten maken.

2024-05-24 12:20 UTC, Toffeegaming commented
![image](https://github.com/ZuydUniversity/B2C6_B2C_Backend/assets/74181914/a2c018fe-cc50-4879-b06a-7ad3095deef6)
Deze error is ook nog aanwezig.

2024-05-24 12:49 UTC, Toffeegaming commented on Backend/UnitTest/Helloworldtest.py
Update: ik heb gevonden hoe de ingebouwde tests kunnen werken, is een kleine fix met bestandsnamen en dan via de testclient zelf.
Hiermee voorkomen we mogelijke extra fouten met via cmd runnen en kunnen we in de test pipeline simpel `pytest Backend/tests/` gebruiken om alle tests te runnen.

2024-05-24 13:26 UTC, Toffeegaming approved these changes
Ik heb wat edits voorgesteld, na een 2e review van iemand anders kan dit de main in.

2024-05-25 18:17 UTC, Megalomizer approved these changes
Voor het runnen werkt `python -m uvicorn main:app --reload` misschien niet en krijg je de error `import error: attempted relative import with no known parent package`.

Indien je dan in de cmd naar de project folder gaat en niet de backend folder kan je het volgende command uitvoeren en dan is dit probleem weg: `python -m uvicorn .backend\main:app --reload`

2024-05-25 18:17 UTC, merged