Created a security-pipeline
ZuydUniversity/B2C6_B2C_Backend pull request #97
Opened 2024-06-13 17:26 UTC by KamikazeShot

Created a security-pipeline with Zap. This should look for vulnerabilities in our website.

2024-06-13 20:12 UTC, Toffeegaming requested changes
Voor zo ver ik zie levert dit errors op, tenzij je het getest hebt en werkt moet je eerst dit bewerken.
Mocht het werken in een test is een screenshot van het resultaat in deze pr voldoende om een approve te krijgen.

2024-06-13 20:12 UTC, Toffeegaming commented on .github/workflows/security-pipeline-team1.yml
> +        run: docker run -u zap -p 8080:8080 -d owasp/zap2docker-stable zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true
deze docker image bestaat niet op dockerhub

2024-06-15 21:53 UTC, KamikazeShot commented
![image](https://github.com/ZuydUniversity/B2C6_B2C_Backend/assets/129733070/806a76c6-153f-4631-982e-39fe8be77a81)

Het werkt in de test-repository

2024-06-17 09:07 UTC, Toffeegaming approved these changes

2024-06-21 07:51 UTC, merged